version: '2'

services:
  redmine-mysql:
    restart: always
    image: sameersbn/mysql:latest
    environment:
      - DB_USER=${REDMINE_DB_USER}
      - DB_PASS=${REDMINE_DB_PASS}
      - DB_NAME=redmine_production
    volumes:
      - /srv/docker/redmine/mysql:/var/lib/mysql

  redmine:
    restart: always
    image: sameersbn/redmine:latest
    container_name: redmine
    depends_on:
      - redmine-mysql
    networks:
      - default
      - local-link
    volumes:
      - /srv/docker/redmine/redmine:/home/redmine/data
    environment:
      - VIRTUAL_HOST=${REDMINE_VIRTUAL_HOST}

      - TZ=Asia/Tokyo

      - DB_ADAPTER=mysql2
      - DB_HOST=redmine-mysql
      - DB_PORT=3306
      - DB_USER=${REDMINE_DB_USER}
      - DB_PASS=${REDMINE_DB_PASS}
      - DB_NAME=redmine_production

      - REDMINE_PORT=
      - REDMINE_HTTPS=false
      - REDMINE_RELATIVE_URL_ROOT=
      - REDMINE_SECRET_TOKEN=

      - REDMINE_SUDO_MODE_ENABLED=false
      - REDMINE_SUDO_MODE_TIMEOUT=15

      - REDMINE_CONCURRENT_UPLOADS=2

      - REDMINE_BACKUP_SCHEDULE=
      - REDMINE_BACKUP_EXPIRY=
      - REDMINE_BACKUP_TIME=

      - SMTP_ENABLED=true
      - SMTP_METHOD=smtp
      - SMTP_DOMAIN=smtp.gmail.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=login

      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=${IMAP_USER}
      - IMAP_PASS=${IMAP_PASS}
      - IMAP_SSL=true
      - IMAP_INTERVAL=30

networks:
  local-link:
    external: true
